/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Analytics { 'formSubmissions' : bigint, 'visitors' : bigint }
export interface Application {
  'status' : Status,
  'paymentStatus' : PaymentStatus,
  'applicationId' : ApplicationId,
  'date' : string,
  'name' : string,
  'email' : string,
  'address' : string,
  'stripePaymentId' : [] | [string],
  'phone' : string,
  'certificateIssued' : boolean,
  'course' : string,
}
export type ApplicationId = string;
export interface ApplicationStageInfo {
  'applicationId' : ApplicationId,
  'stage' : string,
}
export interface ApplicationStatusInfo {
  'status' : Status,
  'applicationId' : ApplicationId,
  'date' : string,
  'name' : string,
  'course' : string,
}
export interface Course {
  'title' : string,
  'duration' : string,
  'fees' : string,
  'icon' : string,
  'description' : string,
  'category' : string,
  'skills' : Array<string>,
  'careerOpportunities' : Array<string>,
}
export interface IdCardData {
  'pin' : string,
  'applicationId' : ApplicationId,
  'name' : string,
  'registrationNumber' : string,
  'email' : string,
  'issuedDate' : string,
  'phone' : string,
  'rollNo' : string,
  'course' : string,
}
export interface Inquiry {
  'name' : string,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export type PaymentStatus = { 'paid' : null } |
  { 'unpaid' : null };
export interface Review {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'feedback' : string,
  'email' : string,
  'rating' : bigint,
  'course' : string,
}
export interface ReviewInput {
  'name' : string,
  'feedback' : string,
  'email' : string,
  'rating' : bigint,
  'course' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export type Status = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface SubAdminInfo { 'name' : string, 'email' : string }
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCourse' : ActorMethod<[Course], undefined>,
  'addReviewByAdmin' : ActorMethod<
    [ReviewInput],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'approveApplication' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createDefaultCheckoutSession' : ActorMethod<[string, string], string>,
  'createSubAdmin' : ActorMethod<[string, string, string, string], undefined>,
  'deleteCourse' : ActorMethod<[string], undefined>,
  'deleteReview' : ActorMethod<[string], undefined>,
  'deleteSubAdmin' : ActorMethod<[string], undefined>,
  'getAllApplications' : ActorMethod<[], Array<Application>>,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getAnalytics' : ActorMethod<[], Analytics>,
  'getApplicationByEmail' : ActorMethod<[string], [] | [Application]>,
  'getApplicationStages' : ActorMethod<[], Array<ApplicationStageInfo>>,
  'getApplicationStatus' : ActorMethod<
    [ApplicationId],
    [] | [ApplicationStatusInfo]
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCourses' : ActorMethod<[], Array<Course>>,
  'getIdCard' : ActorMethod<[ApplicationId], [] | [IdCardData]>,
  'getIdCardByEmail' : ActorMethod<[string], [] | [IdCardData]>,
  'getReviews' : ActorMethod<[], Array<Review>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getSubAdmins' : ActorMethod<[], Array<SubAdminInfo>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCertificateIssued' : ActorMethod<[string], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'issueCertificate' : ActorMethod<[string], undefined>,
  'issueIdCard' : ActorMethod<[ApplicationId], boolean>,
  'recordVisit' : ActorMethod<[], undefined>,
  'rejectApplication' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAdminCredentials' : ActorMethod<
    [string, string, string, string, string],
    boolean
  >,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitApplication' : ActorMethod<[Application], ApplicationId>,
  'submitInquiry' : ActorMethod<[string, string, string, string], undefined>,
  'submitReview' : ActorMethod<
    [ReviewInput],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateApplicationStage' : ActorMethod<[ApplicationId, string], undefined>,
  'updateCourse' : ActorMethod<[Course], undefined>,
  'updatePaymentStatus' : ActorMethod<[string, string, boolean], undefined>,
  'updateReview' : ActorMethod<[string, ReviewInput], boolean>,
  'verifyAdminCredentials' : ActorMethod<[string, string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];