/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Course = IDL.Record({
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'fees' : IDL.Text,
  'icon' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
  'careerOpportunities' : IDL.Vec(IDL.Text),
});
export const ReviewInput = IDL.Record({
  'name' : IDL.Text,
  'feedback' : IDL.Text,
  'email' : IDL.Text,
  'rating' : IDL.Nat,
  'course' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Status = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'paid' : IDL.Null,
  'unpaid' : IDL.Null,
});
export const ApplicationId = IDL.Text;
export const Application = IDL.Record({
  'status' : Status,
  'paymentStatus' : PaymentStatus,
  'applicationId' : ApplicationId,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'stripePaymentId' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
  'certificateIssued' : IDL.Bool,
  'course' : IDL.Text,
});
export const Inquiry = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const Analytics = IDL.Record({
  'formSubmissions' : IDL.Nat,
  'visitors' : IDL.Nat,
});
export const ApplicationStageInfo = IDL.Record({
  'applicationId' : ApplicationId,
  'stage' : IDL.Text,
});
export const ApplicationStatusInfo = IDL.Record({
  'status' : Status,
  'applicationId' : ApplicationId,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'course' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const IdCardData = IDL.Record({
  'pin' : IDL.Text,
  'applicationId' : ApplicationId,
  'name' : IDL.Text,
  'registrationNumber' : IDL.Text,
  'email' : IDL.Text,
  'issuedDate' : IDL.Text,
  'phone' : IDL.Text,
  'rollNo' : IDL.Text,
  'course' : IDL.Text,
});
export const Review = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'feedback' : IDL.Text,
  'email' : IDL.Text,
  'rating' : IDL.Nat,
  'course' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const SubAdminInfo = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCourse' : IDL.Func([Course], [], []),
  'addReviewByAdmin' : IDL.Func(
      [ReviewInput],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'approveApplication' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createDefaultCheckoutSession' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createSubAdmin' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'deleteCourse' : IDL.Func([IDL.Text], [], []),
  'deleteReview' : IDL.Func([IDL.Text], [], []),
  'deleteSubAdmin' : IDL.Func([IDL.Text], [], []),
  'getAllApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getAnalytics' : IDL.Func([], [Analytics], ['query']),
  'getApplicationByEmail' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(Application)],
      ['query'],
    ),
  'getApplicationStages' : IDL.Func(
      [],
      [IDL.Vec(ApplicationStageInfo)],
      ['query'],
    ),
  'getApplicationStatus' : IDL.Func(
      [ApplicationId],
      [IDL.Opt(ApplicationStatusInfo)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getIdCard' : IDL.Func([ApplicationId], [IDL.Opt(IdCardData)], ['query']),
  'getIdCardByEmail' : IDL.Func([IDL.Text], [IDL.Opt(IdCardData)], ['query']),
  'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getSubAdmins' : IDL.Func([], [IDL.Vec(SubAdminInfo)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCertificateIssued' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'issueCertificate' : IDL.Func([IDL.Text], [], []),
  'issueIdCard' : IDL.Func([ApplicationId], [IDL.Bool], []),
  'recordVisit' : IDL.Func([], [], []),
  'rejectApplication' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAdminCredentials' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitApplication' : IDL.Func([Application], [ApplicationId], []),
  'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'submitReview' : IDL.Func(
      [ReviewInput],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateApplicationStage' : IDL.Func([ApplicationId, IDL.Text], [], []),
  'updateCourse' : IDL.Func([Course], [], []),
  'updatePaymentStatus' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [], []),
  'updateReview' : IDL.Func([IDL.Text, ReviewInput], [IDL.Bool], []),
  'verifyAdminCredentials' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Course = IDL.Record({
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'fees' : IDL.Text,
    'icon' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
    'careerOpportunities' : IDL.Vec(IDL.Text),
  });
  const ReviewInput = IDL.Record({
    'name' : IDL.Text,
    'feedback' : IDL.Text,
    'email' : IDL.Text,
    'rating' : IDL.Nat,
    'course' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Status = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({ 'paid' : IDL.Null, 'unpaid' : IDL.Null });
  const ApplicationId = IDL.Text;
  const Application = IDL.Record({
    'status' : Status,
    'paymentStatus' : PaymentStatus,
    'applicationId' : ApplicationId,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'stripePaymentId' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
    'certificateIssued' : IDL.Bool,
    'course' : IDL.Text,
  });
  const Inquiry = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Analytics = IDL.Record({
    'formSubmissions' : IDL.Nat,
    'visitors' : IDL.Nat,
  });
  const ApplicationStageInfo = IDL.Record({
    'applicationId' : ApplicationId,
    'stage' : IDL.Text,
  });
  const ApplicationStatusInfo = IDL.Record({
    'status' : Status,
    'applicationId' : ApplicationId,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'course' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const IdCardData = IDL.Record({
    'pin' : IDL.Text,
    'applicationId' : ApplicationId,
    'name' : IDL.Text,
    'registrationNumber' : IDL.Text,
    'email' : IDL.Text,
    'issuedDate' : IDL.Text,
    'phone' : IDL.Text,
    'rollNo' : IDL.Text,
    'course' : IDL.Text,
  });
  const Review = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'feedback' : IDL.Text,
    'email' : IDL.Text,
    'rating' : IDL.Nat,
    'course' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const SubAdminInfo = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCourse' : IDL.Func([Course], [], []),
    'addReviewByAdmin' : IDL.Func(
        [ReviewInput],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'approveApplication' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createDefaultCheckoutSession' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createSubAdmin' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'deleteCourse' : IDL.Func([IDL.Text], [], []),
    'deleteReview' : IDL.Func([IDL.Text], [], []),
    'deleteSubAdmin' : IDL.Func([IDL.Text], [], []),
    'getAllApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getAnalytics' : IDL.Func([], [Analytics], ['query']),
    'getApplicationByEmail' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Application)],
        ['query'],
      ),
    'getApplicationStages' : IDL.Func(
        [],
        [IDL.Vec(ApplicationStageInfo)],
        ['query'],
      ),
    'getApplicationStatus' : IDL.Func(
        [ApplicationId],
        [IDL.Opt(ApplicationStatusInfo)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getIdCard' : IDL.Func([ApplicationId], [IDL.Opt(IdCardData)], ['query']),
    'getIdCardByEmail' : IDL.Func([IDL.Text], [IDL.Opt(IdCardData)], ['query']),
    'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getSubAdmins' : IDL.Func([], [IDL.Vec(SubAdminInfo)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCertificateIssued' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'issueCertificate' : IDL.Func([IDL.Text], [], []),
    'issueIdCard' : IDL.Func([ApplicationId], [IDL.Bool], []),
    'recordVisit' : IDL.Func([], [], []),
    'rejectApplication' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAdminCredentials' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitApplication' : IDL.Func([Application], [ApplicationId], []),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitReview' : IDL.Func(
        [ReviewInput],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateApplicationStage' : IDL.Func([ApplicationId, IDL.Text], [], []),
    'updateCourse' : IDL.Func([Course], [], []),
    'updatePaymentStatus' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [], []),
    'updateReview' : IDL.Func([IDL.Text, ReviewInput], [IDL.Bool], []),
    'verifyAdminCredentials' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };