/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Status = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Application = IDL.Record({
  'status' : Status,
  'applicationId' : IDL.Text,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'course' : IDL.Text,
});
export const Course = IDL.Record({
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'icon' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const Inquiry = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveApplication' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
  'getAllApplicationsByStatus' : IDL.Func(
      [Status],
      [IDL.Vec(Application)],
      ['query'],
    ),
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getApplicationStatus' : IDL.Func([IDL.Text], [Status], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourse' : IDL.Func([IDL.Text], [Course], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectApplication' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Status = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Application = IDL.Record({
    'status' : Status,
    'applicationId' : IDL.Text,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'course' : IDL.Text,
  });
  const Course = IDL.Record({
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'icon' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const Inquiry = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveApplication' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
    'getAllApplicationsByStatus' : IDL.Func(
        [Status],
        [IDL.Vec(Application)],
        ['query'],
      ),
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getApplicationStatus' : IDL.Func([IDL.Text], [Status], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourse' : IDL.Func([IDL.Text], [Course], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectApplication' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };