/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Application {
  'status' : Status,
  'applicationId' : string,
  'date' : string,
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
  'course' : string,
}
export interface Course {
  'title' : string,
  'duration' : string,
  'icon' : string,
  'description' : string,
  'category' : string,
}
export interface Inquiry {
  'name' : string,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export type Status = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveApplication' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllApplications' : ActorMethod<[], Array<Application>>,
  'getAllApplicationsByStatus' : ActorMethod<[Status], Array<Application>>,
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getApplicationStatus' : ActorMethod<[string], Status>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCourse' : ActorMethod<[string], Course>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectApplication' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitApplication' : ActorMethod<
    [string, string, string, string, string, string, string],
    undefined
  >,
  'submitInquiry' : ActorMethod<[string, string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];